const express = require('express');
const router = express.Router();
const FPDF = require('node-fpdf');
const {
  getOverallSummary,
  getInstructorSectionSummary,
  getInstructorIndividualResponses,
} = require('../services/googleSheetsService');
const { enforcePermission } = require("../middleware/rbacMiddleware");
const {
  generateDigitalSignature,
  attachSignatureToPdf,
} = require('../utils/signature');

const formatScore = (value) => {
  if (typeof value === 'number' && Number.isFinite(value)) {
    return Number(value).toFixed(2);
  }
  return '—';
};

const describeScore = (score) => {
  const value = Number(score);
  if (!Number.isFinite(value) || value <= 0) return 'No Data';
  if (value >= 4.5) return 'Outstanding';
  if (value >= 4.0) return 'Very Satisfactory';
  if (value >= 3.5) return 'Satisfactory';
  if (value >= 3.0) return 'Fair';
  if (value >= 2.5) return 'Needs Improvement';
  return 'Poor';
};

const formatDateTime = () => {
  try {
    return new Intl.DateTimeFormat('en-PH', {
      dateStyle: 'medium',
      timeStyle: 'short',
    }).format(new Date());
  } catch (error) {
    return new Date().toLocaleString();
  }
};

router.post('/form-summary', enforcePermission('generatePdfFormSummary'), async (req, res) => {
  try {
    const { formId } = req.body || {};
    if (!formId) {
      return res.status(400).json({ success: false, message: 'formId is required.' });
    }

    const summary = await getOverallSummary(formId);
    const instructors = Array.isArray(summary?.instructors) ? summary.instructors : [];

    if (!instructors.length) {
      return res.status(404).json({ success: false, message: 'No instructors found for the selected evaluation form.' });
    }

    const pdf = new FPDF('P', 'mm', 'A4');
    pdf.AddPage();

    // Header
    pdf.SetFont('Helvetica', 'B', 12);
    pdf.Cell(0, 6, 'BUKIDNON STATE UNIVERSITY', 0, 1, 'C');
    pdf.SetFont('Helvetica', '', 10);
    pdf.Cell(0, 5, 'Malaybalay City, Bukidnon, 8700', 0, 1, 'C');
    pdf.Cell(0, 5, 'Tel (088) 813-5661 to 5663; TeleFax (088) 813-2717', 0, 1, 'C');
    pdf.SetTextColor(34, 87, 149);
    pdf.Cell(0, 5, 'www.buksu.edu.ph', 0, 1, 'C');
    pdf.SetTextColor(0, 0, 0);
    pdf.SetFont('Helvetica', 'I', 10);
    pdf.Cell(0, 5, 'College of Technologies', 0, 1, 'C');

    pdf.Ln(4);
    pdf.SetFont('Helvetica', 'B', 13);
    pdf.Cell(0, 8, 'Instructor Performance Summary', 0, 1, 'C');
    pdf.SetFont('Helvetica', '', 10);
    pdf.Cell(0, 6, `Evaluation Form: ${summary?.formTitle || 'N/A'}`, 0, 1, 'C');
    pdf.Cell(0, 5, `Generated: ${formatDateTime()}`, 0, 1, 'C');
    pdf.Ln(6);

    // Table Header
    const columnWidths = [70, 35, 45, 35];
    pdf.SetFillColor(35, 56, 118);
    pdf.SetTextColor(255, 255, 255);
    pdf.SetFont('Helvetica', 'B', 10);
    pdf.Cell(columnWidths[0], 8, 'Instructor', 1, 0, 'L', true);
    pdf.Cell(columnWidths[1], 8, 'Total Average', 1, 0, 'C', true);
    pdf.Cell(columnWidths[2], 8, 'Rating Equivalent', 1, 0, 'C', true);
    pdf.Cell(columnWidths[3], 8, 'Reclassification', 1, 1, 'C', true);

    pdf.SetFont('Helvetica', '', 9);
    pdf.SetTextColor(0, 0, 0);

    instructors.forEach((instructor, index) => {
      const rowFill = index % 2 === 0;
      if (rowFill) {
        pdf.SetFillColor(245, 247, 255);
      } else {
        pdf.SetFillColor(255, 255, 255);
      }

      const instructorName = instructor.instructorName || 'Unknown Instructor';
      const totalAverage =
        typeof instructor.totalAverage === 'number'
          ? instructor.totalAverage
          : instructor.categoryBreakdown?.totalAverage;
      const ratingEquivalent = instructor.descriptiveRating || '—';
      const reclassification =
        typeof instructor.facultyReclassificationScore === 'number'
          ? `${instructor.facultyReclassificationScore}`
          : instructor.categoryBreakdown?.facultyReclassificationScore
          ? `${instructor.categoryBreakdown.facultyReclassificationScore}`
          : '—';

      pdf.Cell(columnWidths[0], 8, instructorName.substring(0, 45), 1, 0, 'L', true);
      pdf.Cell(columnWidths[1], 8, formatScore(totalAverage), 1, 0, 'C', true);
      pdf.Cell(columnWidths[2], 8, ratingEquivalent, 1, 0, 'C', true);
      pdf.Cell(columnWidths[3], 8, reclassification, 1, 1, 'C', true);
    });

    pdf.Ln(6);
    pdf.SetFont('Helvetica', '', 10);
    pdf.Cell(0, 6, `Total Instructors: ${instructors.length}`, 0, 1);
    pdf.Cell(0, 6, `Total Responses: ${summary?.totalResponses ?? 0}`, 0, 1);

    pdf.SetY(-15);
    pdf.SetFont('Helvetica', 'I', 8);
    pdf.Cell(0, 10, `Generated by the Dean Dashboard System • Page ${pdf.PageNo()}`, 0, 0, 'C');

    const pdfBinary = pdf.Output('S');
    let pdfBuffer = Buffer.from(pdfBinary, 'binary');

    // Attach digital signature (Dean user)
    const user = req.user || { email: 'dean@buksu.edu.ph', role: 'dean' };
    const signature = generateDigitalSignature(user, pdfBuffer);
    pdfBuffer = await attachSignatureToPdf(pdfBuffer, signature, user);

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader(
      'Content-Disposition',
      `attachment; filename="evaluation-form-summary-${summary?.formTitle || 'report'}.pdf"`
    );
    return res.send(pdfBuffer);
  } catch (error) {
    console.error('Failed to generate form summary PDF:', error);
    return res.status(500).json({ success: false, message: 'Failed to generate PDF report.', error: error.message });
  }
});

router.post('/instructor-evaluation', enforcePermission('generateInstructorReport'), async (req, res) => {
  try {
    const { formId, email } = req.body || {};
    if (!formId) {
      return res.status(400).json({ success: false, message: 'formId is required.' });
    }

    const instructorEmail = (email || req.user?.email || '').toLowerCase().trim();
    if (!instructorEmail) {
      return res.status(401).json({ success: false, message: 'Unable to determine instructor identity.' });
    }

    const summary = await getOverallSummary(formId);
    const instructors = Array.isArray(summary?.instructors) ? summary.instructors : [];
    const instructor = instructors.find(
      (item) => (item.instructorEmail || '').toLowerCase().trim() === instructorEmail
    );

    if (!instructor) {
      return res.status(404).json({
        success: false,
        message: 'No evaluation data found for this instructor in the selected form.',
      });
    }

    const totalAverage =
      typeof instructor.totalAverage === 'number'
        ? instructor.totalAverage
        : instructor.categoryBreakdown?.totalAverage;
    const ratingEquivalent =
      instructor.descriptiveRating ||
      instructor.categoryBreakdown?.descriptiveRating ||
      describeScore(totalAverage);
    const reclassification =
      typeof instructor.facultyReclassificationScore === 'number'
        ? instructor.facultyReclassificationScore
        : instructor.categoryBreakdown?.facultyReclassificationScore ??
          Math.round(((totalAverage || 0) / 5) * 100);

    // Metadata fields to exclude from question ratings
    const metadataKeywords = [
      'student name', 'name', 'first name', 'last name', 'student first name', 'student last name',
      'full name', 'fullname', 'studentname', 'student_name',
      'year level', 'yearlevel', 'year_level', 'yr level', 'year',
      'section code', 'subject code', 'select instructor', 'course',
      'student id', 'student email', 'student email address',
      'timestamp', 'instructor name', 'instructor email'
    ];

    const shouldExcludeQuestion = (questionText) => {
      if (!questionText) return true;
      const normalized = String(questionText).toLowerCase().trim();
      return metadataKeywords.some(keyword => normalized === keyword || normalized.includes(keyword));
    };

    const questionRows = (instructor.questions || [])
      .filter((question) => {
        const text = question.question || '';
        return !shouldExcludeQuestion(text);
      })
      .map((question, index) => {
        const text = question.question || `Question ${index + 1}`;
        const average =
          question.stats && question.stats.numericCount > 0 ? formatScore(question.stats.average) : '—';

        // Prefer unique text answers; fall back to non-numeric answers
        const rawAnswers = Array.isArray(question.uniqueTextAnswers) && question.uniqueTextAnswers.length
          ? question.uniqueTextAnswers
          : Array.isArray(question.answers)
          ? question.answers
          : [];

        const textResponses = rawAnswers
          .map((resp) => (resp == null ? '' : String(resp).trim()))
          .filter((resp) => resp && !/^-?\d+(\.\d+)?$/.test(resp)); // filter out pure numeric values

        return {
          label: `${index + 1}. ${text}`,
          average,
          textResponses,
        };
      });

    const pdf = new FPDF('P', 'mm', 'A4');
    pdf.AddPage();
    const marginX = 14;
    const usableWidth = 210 - marginX * 2;

    const ensureSpace = (height = 10) => {
      const getY = typeof pdf.GetY === 'function' ? pdf.GetY.bind(pdf) : () => pdf.y || 0;
      const currentY = getY();
      if (currentY + height > 270) {
        pdf.AddPage();
      }
    };

    // Header
    pdf.SetFont('Helvetica', 'B', 12);
    pdf.Cell(0, 6, 'BUKIDNON STATE UNIVERSITY', 0, 1, 'C');
    pdf.SetFont('Helvetica', '', 10);
    pdf.Cell(0, 5, 'Malaybalay City, Bukidnon, 8700', 0, 1, 'C');
    pdf.Cell(0, 5, 'Tel (088) 813-5661 to 5663; TeleFax (088) 813-2717;', 0, 1, 'C');
    pdf.SetTextColor(34, 87, 149);
    pdf.Cell(0, 5, 'www.buksu.edu.ph', 0, 1, 'C');
    pdf.SetTextColor(0, 0, 0);
    pdf.SetFont('Helvetica', 'I', 10);
    pdf.Cell(0, 5, 'College of Technologies', 0, 1, 'C');

    pdf.Ln(4);
    pdf.SetFont('Helvetica', 'B', 14);
    pdf.Cell(0, 8, 'Instructor Performance Report', 0, 1, 'C');
    pdf.SetFont('Helvetica', '', 11);
    pdf.Cell(0, 6, `Evaluation Form: ${summary?.formTitle || 'N/A'}`, 0, 1, 'C');
    pdf.Cell(0, 5, `Generated: ${formatDateTime()}`, 0, 1, 'C');
    pdf.Ln(4);

    // Instructor details
    pdf.SetFont('Helvetica', 'B', 11);
    pdf.Cell(0, 6, 'Instructor Details', 0, 1);
    pdf.SetFont('Helvetica', '', 10);
    pdf.Cell(usableWidth / 2, 6, `Instructor: ${instructor.instructorName || 'Unknown'}`, 0, 0);
    pdf.Cell(usableWidth / 2, 6, `Department: ${instructor.department || '—'}`, 0, 1);
    pdf.Cell(usableWidth / 2, 6, `Email: ${instructor.instructorEmail || instructorEmail}`, 0, 0);
    pdf.Cell(usableWidth / 2, 6, `Total Responses: ${instructor.totalResponses || 0}`, 0, 1);
    pdf.Ln(4);

    // Question ratings + responses table (main content)
    pdf.SetFont('Helvetica', 'B', 11);
    pdf.Cell(0, 6, 'Question Ratings', 0, 1);
    pdf.SetFont('Helvetica', '', 10);

    const questionColWidth = Math.floor(usableWidth * 0.45);
    const averageColWidth = 20;
    const responsesColWidth = usableWidth - questionColWidth - averageColWidth;

    const drawQuestionsHeader = () => {
      pdf.SetFillColor(35, 56, 118);
      pdf.SetTextColor(255, 255, 255);
      pdf.SetFont('Helvetica', 'B', 10);
      pdf.Cell(questionColWidth, 7, 'Question', 1, 0, 'L', true);
      pdf.Cell(averageColWidth, 7, 'Average', 1, 0, 'C', true);
      pdf.Cell(responsesColWidth, 7, 'Responses', 1, 1, 'L', true);
      pdf.SetTextColor(0, 0, 0);
      pdf.SetFont('Helvetica', '', 10);
    };

    if (questionRows.length) {
      drawQuestionsHeader();

      questionRows.forEach((row) => {
        ensureSpace(12);

        const questionStartX = typeof pdf.GetX === 'function' ? pdf.GetX() : marginX;
        const questionStartY = typeof pdf.GetY === 'function' ? pdf.GetY() : 0;

        // Question text
        pdf.MultiCell(questionColWidth, 6, row.label, 0, 'L');
        const afterQuestionY = typeof pdf.GetY === 'function' ? pdf.GetY() : questionStartY + 6;
        const questionHeight = afterQuestionY - questionStartY;

        // Average rating
        pdf.SetXY(questionStartX + questionColWidth, questionStartY);
        pdf.MultiCell(averageColWidth, 6, row.average || '—', 0, 'C');
        const afterAverageY = typeof pdf.GetY === 'function' ? pdf.GetY() : questionStartY + 6;
        const averageHeight = afterAverageY - questionStartY;

        // Responses
        const responseText = row.textResponses?.length
          ? row.textResponses.map((resp, idx) => `${idx + 1}. ${resp}`).join('\n')
          : '—';

        pdf.SetXY(questionStartX + questionColWidth + averageColWidth, questionStartY);
        pdf.MultiCell(responsesColWidth, 6, responseText, 0, 'L');
        const afterResponsesY = typeof pdf.GetY === 'function' ? pdf.GetY() : questionStartY + 6;
        const responsesHeight = afterResponsesY - questionStartY;

        const rowHeight = Math.max(questionHeight, averageHeight, responsesHeight, 6);
        pdf.Rect(questionStartX, questionStartY, questionColWidth, rowHeight);
        pdf.Rect(questionStartX + questionColWidth, questionStartY, averageColWidth, rowHeight);
        pdf.Rect(questionStartX + questionColWidth + averageColWidth, questionStartY, responsesColWidth, rowHeight);
        pdf.SetXY(questionStartX, questionStartY + rowHeight);

        const nextY = typeof pdf.GetY === 'function' ? pdf.GetY() : questionStartY + rowHeight;
        if (nextY > 265) {
          pdf.AddPage();
          pdf.SetFont('Helvetica', 'B', 11);
          pdf.Cell(0, 6, 'Question Ratings (continued)', 0, 1);
          drawQuestionsHeader();
        }
      });
    } else {
      pdf.SetFont('Helvetica', 'I', 9);
      pdf.Cell(0, 6, 'No question statistics available.', 0, 1);
      pdf.SetFont('Helvetica', '', 10);
    }

    pdf.Ln(6);

    // Instructor summary row (like department report, but for a single instructor)
    pdf.SetFont('Helvetica', 'B', 11);
    pdf.Cell(0, 6, 'Instructor Summary', 0, 1);
    pdf.SetFillColor(35, 56, 118);
    pdf.SetTextColor(255, 255, 255);
    pdf.SetFont('Helvetica', 'B', 10);
    const summaryColWidths = [70, 35, 45, 35];
    pdf.Cell(summaryColWidths[0], 7, 'Instructor', 1, 0, 'L', true);
    pdf.Cell(summaryColWidths[1], 7, 'Total Average', 1, 0, 'C', true);
    pdf.Cell(summaryColWidths[2], 7, 'Rating Equivalent', 1, 0, 'C', true);
    pdf.Cell(summaryColWidths[3], 7, 'Faculty Reclassification', 1, 1, 'C', true);

    pdf.SetTextColor(0, 0, 0);
    pdf.SetFont('Helvetica', '', 10);
    pdf.Cell(summaryColWidths[0], 7, instructor.instructorName || 'Unknown Instructor', 1, 0, 'L');
    pdf.Cell(summaryColWidths[1], 7, formatScore(totalAverage), 1, 0, 'C');
    pdf.Cell(summaryColWidths[2], 7, ratingEquivalent, 1, 0, 'C');
    pdf.Cell(summaryColWidths[3], 7, `${reclassification ?? '—'}`, 1, 1, 'C');

    // Footer
    pdf.SetY(-20);
    pdf.SetFont('Helvetica', 'I', 8);
    pdf.Cell(0, 10, 'Generated by the Dean Dashboard System • Page ' + pdf.PageNo(), 0, 0, 'C');

    const pdfBinary = pdf.Output('S');
    let pdfBuffer = Buffer.from(pdfBinary, 'binary');

    const user = req.user || { email: instructorEmail, role: 'dean' };
    const signature = generateDigitalSignature(user, pdfBuffer);
    pdfBuffer = await attachSignatureToPdf(pdfBuffer, signature, user);

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader(
      'Content-Disposition',
      `attachment; filename="instructor-evaluation-${(instructor.instructorName || 'report')
        .replace(/\s+/g, '-')
        .toLowerCase()}.pdf"`
    );
    return res.send(pdfBuffer);
  } catch (error) {
    console.error('Failed to generate instructor evaluation PDF:', error);
    return res
      .status(500)
      .json({ success: false, message: 'Failed to generate PDF report.', error: error.message });
  }
});

module.exports = router;

