import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { generateDigitalSignature, getCurrentUserForSignature } from './signature';

const DEFAULT_TAGLINE = 'Generated by the Dean Dashboard System';
const FALLBACK_TEXT = 'Not specified';
const DEFAULT_LOGO_PATHS = {
  left: '/buksu-logo.png',
  right: '/cot-logo.jpg',
};

const resolveAssetPath = (src) => {
  if (!src) return null;
  if (src.startsWith('data:') || /^https?:\/\//i.test(src)) {
    return src;
  }
  const baseUrl = typeof window !== 'undefined' ? window.location.origin : '';
  if (!baseUrl) {
    return src.startsWith('/') ? src : `/${src}`;
  }
  return src.startsWith('/') ? `${baseUrl}${src}` : `${baseUrl}/${src}`;
};

const fetchImageAsDataUrl = async (src) => {
  if (!src) return null;
  const resolved = resolveAssetPath(src);
  try {
    const response = await fetch(resolved, { cache: 'force-cache' });
    if (!response.ok) {
      throw new Error(`Unable to load logo: ${response.statusText}`);
    }
    const blob = await response.blob();
    return await new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
  } catch (error) {
    console.warn('[PDF] Failed to load image for header', src, error);
    return null;
  }
};

const getImageFormat = (dataUrl) => {
  if (!dataUrl || typeof dataUrl !== 'string') return 'PNG';
  if (dataUrl.startsWith('data:image/jpeg') || dataUrl.startsWith('data:image/jpg')) return 'JPEG';
  if (dataUrl.startsWith('data:image/webp')) return 'WEBP';
  return 'PNG';
};

const formatScore = (value) => {
  if (typeof value === 'number' && Number.isFinite(value)) {
    return Number(value).toFixed(2);
  }
  return '—';
};

const asText = (value, fallback = FALLBACK_TEXT) => {
  if (value === 0) {
    return '0';
  }
  return value ? String(value) : fallback;
};

const gatherQuestionList = (payload = {}) => {
  if (Array.isArray(payload.allQuestions) && payload.allQuestions.length) {
    return payload.allQuestions;
  }

  const merged = [
    ...(Array.isArray(payload.generalIndicators) ? payload.generalIndicators : []),
    ...(Array.isArray(payload.masteryIndicators) ? payload.masteryIndicators : []),
  ];

  return merged;
};

// Metadata fields to exclude from question tables
const METADATA_KEYWORDS = [
  'student name', 'name', 'first name', 'last name', 'student first name', 'student last name',
  'full name', 'fullname', 'studentname', 'student_name',
  'year level', 'yearlevel', 'year_level', 'yr level', 'year',
  'section code', 'subject code', 'select instructor', 'course',
  'student id', 'student email', 'student email address',
  'timestamp', 'instructor name', 'instructor email', 'instructor email address'
];

const shouldExcludeQuestion = (questionText) => {
  if (!questionText) return true;
  const normalized = String(questionText).toLowerCase().trim();
  return METADATA_KEYWORDS.some(keyword => normalized === keyword || normalized.includes(keyword));
};

const buildQuestionRows = (payload) => {
  const questions = gatherQuestionList(payload)
    .filter((question) => {
      const questionText = question?.question || question?.questionText || '';
      return !shouldExcludeQuestion(questionText);
    });

  if (!questions.length) {
    return [['No evaluation questions available', '—']];
  }

  return questions.map((question, index) => {
    const label = question?.question || question?.questionText || `Untitled Question ${index + 1}`;
    return [`${index + 1}. ${label}`, formatScore(question?.average)];
  });
};

const addHeader = (doc, payload = {}, logos = {}) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  const marginX = 14;
  const centerX = pageWidth / 2;
  let currentY = 20;

  const logoHeight = 26;
  const logoWidth = 26;
  const leftLogo = logos.left;
  const rightLogo = logos.right;

  if (leftLogo?.dataUrl) {
    doc.addImage(leftLogo.dataUrl, leftLogo.format, marginX, currentY - logoHeight / 2, logoWidth, logoHeight, undefined, 'FAST');
  }
  if (rightLogo?.dataUrl) {
    doc.addImage(
      rightLogo.dataUrl,
      rightLogo.format,
      pageWidth - marginX - logoWidth,
      currentY - logoHeight / 2,
      logoWidth,
      logoHeight,
      undefined,
      'FAST'
    );
  }

  doc.setFont('times', 'bold');
  doc.setFontSize(12);
  doc.text('BUKIDNON STATE UNIVERSITY', centerX, currentY, { align: 'center' });

  doc.setFont('times', 'normal');
  doc.setFontSize(10);
  doc.text('Malaybalay City, Bukidnon, 8700', centerX, currentY + 5, { align: 'center' });
  doc.text('Tel (088) 813-5661 to 5663; TeleFax (088) 813-2717;', centerX, currentY + 10, { align: 'center' });

  doc.setTextColor(34, 87, 149);
  doc.text('www.buksu.edu.ph', centerX, currentY + 15, { align: 'center' });
  doc.setTextColor(0, 0, 0);

  doc.setFont('times', 'italic');
  doc.text('College of Technologies', centerX, currentY + 21, { align: 'center' });

  currentY += 32;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text(asText(payload.reportTitle || 'Instructor Performance Report'), centerX, currentY, { align: 'center' });

  currentY += 8;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(`Evaluation Form: ${asText(payload.formTitle)}`, centerX, currentY, { align: 'center' });

  currentY += 10;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('Instructor Details', marginX, currentY);

  currentY += 6;
  doc.setFont('helvetica', 'normal');
  const rightColumnX = pageWidth / 2 + 5;
  doc.text(`Instructor: ${asText(payload.instructorName, 'Unknown Instructor')}`, marginX, currentY);
  doc.text(`Semester: ${asText(payload.semester)}`, rightColumnX, currentY);

  currentY += 6;
  doc.text(`Department: ${asText(payload.department, '—')}`, marginX, currentY);
  doc.text(`Academic Year: ${asText(payload.academicYear)}`, rightColumnX, currentY);

  currentY += 8;
  doc.text(`Total Respondents: ${asText(payload.totalRespondents, '0')}`, marginX, currentY);

  currentY += 10;
  doc.setDrawColor(229, 231, 235);
  doc.setLineWidth(0.2);
  doc.line(marginX, currentY, pageWidth - marginX, currentY);

  return currentY + 6;
};

const addSummaryTable = (doc, payload, startY) => {
  const summaryRows = [
    ['Total Average', formatScore(payload.totalAverage)],
    ['Rating Equivalent', asText(payload.totalDescriptor, '—')],
  ];

  if (typeof payload.conversionScore === 'number') {
    summaryRows.push(['Faculty Reclassification Score', `${payload.conversionScore}`]);
  }

  autoTable(doc, {
    head: [['Summary', 'Value']],
    body: summaryRows,
    startY,
    theme: 'grid',
    styles: { fontSize: 10, cellPadding: 3 },
    headStyles: { fillColor: [102, 126, 234], textColor: 255 },
    columnStyles: {
      0: { cellWidth: 90 },
      1: { cellWidth: 80 },
    },
    margin: { left: 14, right: 14 },
  });

  return doc.lastAutoTable?.finalY || startY;
};

const addSectionSummaryTable = (doc, payload, startY) => {
  const sections = Array.isArray(payload.sectionSummary) ? payload.sectionSummary : [];
  // Only extract the three fields we need: sectionCode, respondents/totalStudents, and average
  // Explicitly exclude any student names, year levels, or other personal information
  const rows = sections.length
    ? sections.map((row, idx) => {
        // Only extract the specific fields we want to display
        const sectionCode = row.sectionCode || `Section ${idx + 1}`;
        const respondents = row.respondents || 0;
        const totalStudents = row.totalStudents || 0;
        const average = formatScore(row.average);
        
        // Return only the three columns: Section Code, Respondents, Average
        // No student names, year levels, or other personal data
        return [
          sectionCode,
          `${respondents} / ${totalStudents}`,
          average,
        ];
      })
    : [['No section data available', '—', '—']];

  autoTable(doc, {
    head: [['Section Code', 'Respondents', 'Average']],
    body: rows,
    startY,
    theme: 'grid',
    styles: { fontSize: 10, cellPadding: 3, valign: 'middle' },
    headStyles: { fillColor: [46, 125, 50], textColor: 255 },
    columnStyles: {
      0: { cellWidth: 80 },
      1: { cellWidth: 50, halign: 'center' },
      2: { cellWidth: 40, halign: 'center' },
    },
    margin: { left: 14, right: 14 },
  });

  return doc.lastAutoTable?.finalY || startY;
};

const addQuestionTable = (doc, payload, startY) => {
  autoTable(doc, {
    head: [['Question', 'Average Rating']],
    body: buildQuestionRows(payload),
    startY,
    theme: 'grid',
    styles: { fontSize: 9, cellPadding: 3, valign: 'middle' },
    headStyles: { fillColor: [35, 56, 118], textColor: 255 },
    columnStyles: {
      0: { cellWidth: 130 },
      1: { cellWidth: 40, halign: 'center' },
    },
    margin: { left: 14, right: 14 },
  });

  return doc.lastAutoTable?.finalY || startY;
};

const addCommentsSection = (doc, payload, startY) => {
  const comments = Array.isArray(payload.textResponses) ? payload.textResponses : [];
  if (!comments.length) {
    return startY;
  }

  const rows = comments.map((response, index) => [
    `${index + 1}. ${response.question || 'Question'}`,
    response.response || '—',
  ]);

  autoTable(doc, {
    head: [['Question', 'Comment']],
    body: rows,
    startY,
    theme: 'grid',
    styles: { fontSize: 9, cellPadding: 3, valign: 'top' },
    headStyles: { fillColor: [24, 58, 94], textColor: 255 },
    columnStyles: {
      0: { cellWidth: 70 },
      1: { cellWidth: 100 },
    },
    margin: { left: 14, right: 14 },
  });

  return doc.lastAutoTable?.finalY || startY;
};

const addIndividualResponsesSection = (doc, payload, startY) => {
  const individualResponses = Array.isArray(payload.individualResponses) ? payload.individualResponses : [];
  if (!individualResponses.length) {
    return startY;
  }

  const marginX = 14;
  let currentY = startY;

  // Metadata columns to exclude from display - includes all variations of student name and year level
  const metadataColumns = new Set([
    'timestamp', 'instructor name', 'instructor email', 'instructor email address',
    'student id', 'student email', 'student email address', 'section code',
    'subject code', 'course', 'semester', 'academic year', 'year level', 'year',
    'select instructor', 'student name', 'name', 'first name', 'last name',
    'student first name', 'student last name', 'yearlevel', 'year_level', 'yr level',
    'studentname', 'student_name', 'studentname', 'full name', 'fullname'
  ]);

  const isNumericQuestion = (questionText, allAnswers) => {
    const lowerText = questionText.toLowerCase();
    if (lowerText.includes('(1-5)') || lowerText.includes('rating') || lowerText.includes('rate')) {
      return true;
    }
    if (lowerText.includes('comment') || lowerText.includes('feedback') || lowerText.includes('suggestion')) {
      return false;
    }
    if (allAnswers && allAnswers.length > 0) {
      const numericCount = allAnswers.filter(answer => {
        const num = parseFloat(answer);
        return !isNaN(num) && isFinite(num) && num > 0;
      }).length;
      return numericCount > allAnswers.length / 2;
    }
    return true;
  };

  const questionList = [];
  const questionMap = new Map();

  if (payload.allQuestions && Array.isArray(payload.allQuestions) && payload.allQuestions.length > 0) {
    payload.allQuestions.forEach((q) => {
      const questionText = q.question || q.questionText || '';
      if (questionText && questionText.trim()) {
        const normalized = questionText.trim();
        const lowerHeader = normalized.toLowerCase();
        if (!metadataColumns.has(lowerHeader)) {
          questionList.push({
            text: normalized,
            isNumeric: q.isNumeric !== undefined ? q.isNumeric : (q.questionType === 'rating' || q.questionType === 'multiple_choice')
          });
          questionMap.set(normalized.toLowerCase(), normalized);
        }
      }
    });
  }

  if (individualResponses.length > 0 && individualResponses[0].answers) {
    Object.keys(individualResponses[0].answers).forEach((header) => {
      if (header && header.trim()) {
        const normalized = header.trim();
        const lowerHeader = normalized.toLowerCase();
        if (!metadataColumns.has(lowerHeader) && !questionMap.has(lowerHeader)) {
          const allAnswersForQuestion = individualResponses
            .map(r => {
              const answer = r.answers?.[normalized];
              return answer !== undefined && answer !== null && String(answer).trim() !== '' ? String(answer).trim() : null;
            })
            .filter(a => a !== null);
          
          questionList.push({
            text: normalized,
            isNumeric: isNumericQuestion(normalized, allAnswersForQuestion)
          });
          questionMap.set(lowerHeader, normalized);
        }
      }
    });
  }

  if (questionList.length === 0) {
    return startY;
  }

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  currentY += 10;
  doc.text('Student Responses Summary', marginX, currentY);
  currentY += 4;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text(`Total Respondents: ${individualResponses.length}`, marginX, currentY);
  currentY += 10;

  const tableBody = questionList.map((questionItem, questionIndex) => {
    const questionText = questionItem.text;
    const isNumeric = questionItem.isNumeric;

    if (isNumeric) {
      const answers = [];
      individualResponses.forEach((response) => {
        let answer = response.answers?.[questionText];
        if (answer === undefined || answer === null || answer === '') {
          const matchingKey = Object.keys(response.answers || {}).find(
            (key) => key.toLowerCase().trim() === questionText.toLowerCase().trim()
          );
          if (matchingKey) {
            answer = response.answers[matchingKey];
          }
        }
        if (answer !== undefined && answer !== null && String(answer).trim() !== '') {
          const num = parseFloat(String(answer).trim());
          if (!isNaN(num) && isFinite(num)) {
            answers.push(num);
          }
        }
      });

      let averageText = '—';
      if (answers.length > 0) {
        const average = answers.reduce((sum, val) => sum + val, 0) / answers.length;
        const roundedAverage = Math.round(average * 100) / 100;
        averageText = formatScore(roundedAverage);
      }

      return [`${questionIndex + 1}. ${questionText}`, averageText];
    } else {
      const comments = [];
      individualResponses.forEach((response) => {
        let answer = response.answers?.[questionText];
        if (answer === undefined || answer === null || answer === '') {
          const matchingKey = Object.keys(response.answers || {}).find(
            (key) => key.toLowerCase().trim() === questionText.toLowerCase().trim()
          );
          if (matchingKey) {
            answer = response.answers[matchingKey];
          }
        }
        if (answer !== undefined && answer !== null && String(answer).trim() !== '') {
          comments.push(String(answer).trim());
        }
      });

      let commentsText = '—';
      if (comments.length > 0) {
        commentsText = comments.map((comment, idx) => `${idx + 1}. ${comment}`).join('\n');
      }

      return [`${questionIndex + 1}. ${questionText}`, commentsText];
    }
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const availableWidth = pageWidth - (marginX * 2);
  const questionColumnWidth = availableWidth * 0.4;
  const answerColumnWidth = availableWidth * 0.6;

  autoTable(doc, {
    head: [['Question', 'Average']],
    body: tableBody,
    startY: currentY,
    theme: 'grid',
    styles: { fontSize: 8, cellPadding: 3, valign: 'top' },
    headStyles: { fillColor: [70, 130, 180], textColor: 255, fontSize: 9 },
    columnStyles: {
      0: { cellWidth: questionColumnWidth, fontStyle: 'bold' },
      1: { cellWidth: answerColumnWidth, cellMinHeight: 6 },
    },
    margin: { left: marginX, right: marginX },
    didParseCell: (data) => {
      if (data.column.index === 1 && data.cell.text && String(data.cell.text).includes('\n')) {
        data.cell.text = String(data.cell.text).split('\n');
      } else if (data.column.index === 1 && data.cell.text) {
        const text = String(data.cell.text);
        if (text.length > 80) {
          const words = text.split(' ');
          const lines = [];
          let currentLine = '';
          words.forEach((word) => {
            if ((currentLine + word).length > 80) {
              if (currentLine) lines.push(currentLine.trim());
              currentLine = word + ' ';
            } else {
              currentLine += word + ' ';
            }
          });
          if (currentLine) lines.push(currentLine.trim());
          data.cell.text = lines;
        }
      }
    },
  });

  currentY = doc.lastAutoTable?.finalY || currentY;
  currentY += 10;

  return currentY;
};

const addFooter = (doc, tagline = DEFAULT_TAGLINE, footerText = '') => {
  const pageCount = doc.internal.getNumberOfPages();

  for (let pageNumber = 1; pageNumber <= pageCount; pageNumber += 1) {
    doc.setPage(pageNumber);
    const pageHeight = doc.internal.pageSize.getHeight();
    const pageWidth = doc.internal.pageSize.getWidth();

    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    if (footerText) {
      doc.text(footerText, 14, pageHeight - 13, { maxWidth: pageWidth - 28 });
    }
    doc.text(tagline, 14, pageHeight - 7);
    doc.text(`Page ${pageNumber} of ${pageCount}`, pageWidth - 14, pageHeight - 7, {
      align: 'right',
    });
  }
};

const openPdf = (doc, fileName) => {
  try {
    const blob = doc.output('blob');
    const blobUrl = URL.createObjectURL(blob);
    const popup = window.open(blobUrl);

    if (!popup) {
      doc.save(fileName);
      URL.revokeObjectURL(blobUrl);
      return;
    }

    popup.onload = () => {
      setTimeout(() => URL.revokeObjectURL(blobUrl), 60_000);
    };
  } catch (error) {
    console.error('Unable to open PDF in new tab, falling back to download.', error);
    doc.save(fileName);
  }
};

const generateInstructorReportPdf = async (payload) => {
  if (!payload) {
    throw new Error('Cannot generate PDF without payload data.');
  }

  const leftLogoPath = payload?.headerLogos?.left || DEFAULT_LOGO_PATHS.left;
  const rightLogoPath = payload?.headerLogos?.right || DEFAULT_LOGO_PATHS.right;

  const [leftLogoDataUrl, rightLogoDataUrl] = await Promise.all([
    fetchImageAsDataUrl(leftLogoPath),
    fetchImageAsDataUrl(rightLogoPath),
  ]);

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const headerBottom = addHeader(
    doc,
    payload,
    {
      left: leftLogoDataUrl ? { dataUrl: leftLogoDataUrl, format: getImageFormat(leftLogoDataUrl) } : null,
      right: rightLogoDataUrl ? { dataUrl: rightLogoDataUrl, format: getImageFormat(rightLogoDataUrl) } : null,
    }
  );
  // Instructor dashboard print report: only show the section summary table
  const sectionTableBottom = addSectionSummaryTable(doc, payload, headerBottom + 6);
  // First footer pass
  addFooter(doc, DEFAULT_TAGLINE, '');

  const pdfArrayBuffer = doc.output('arraybuffer');
  const user = getCurrentUserForSignature();
  const { footerText, signatureHash, signatureId } = generateDigitalSignature(user, pdfArrayBuffer);

  doc.setProperties({
    title: `Instructor Performance - ${asText(payload.instructorName, 'Instructor')}`,
    subject: 'Digitally signed instructor performance report',
    author: user.email,
    keywords: `digital-signature,sha256,SignatureID=${signatureId},SignatureHash=${signatureHash}`,
    creator: 'Buksu IT Instructor Evaluation System',
  });

  // Final footer with signature text
  addFooter(doc, DEFAULT_TAGLINE, footerText);

  const normalizedName = asText(payload.instructorName, 'instructor')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    || 'instructor';
  const fileName = `instructor-performance-${normalizedName}.pdf`;
  openPdf(doc, fileName);

  return sectionTableBottom;
};

export default generateInstructorReportPdf;

