import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { generateDigitalSignature, getCurrentUserForSignature } from './signature';

const DEFAULT_TAGLINE = 'Generated by the Dean Dashboard System';
const DEFAULT_LOGO_PATHS = {
  left: '/buksu-logo.png',
  right: '/cot-logo.jpg',
};

const resolveAssetPath = (src) => {
  if (!src) return null;
  if (src.startsWith('data:') || /^https?:\/\//i.test(src)) {
    return src;
  }
  const baseUrl = typeof window !== 'undefined' ? window.location.origin : '';
  if (!baseUrl) {
    return src.startsWith('/') ? src : `/${src}`;
  }
  return src.startsWith('/') ? `${baseUrl}${src}` : `${baseUrl}/${src}`;
};

const fetchImageAsDataUrl = async (src) => {
  if (!src) return null;
  const resolved = resolveAssetPath(src);
  try {
    const response = await fetch(resolved, { cache: 'force-cache' });
    if (!response.ok) {
      throw new Error(`Unable to load logo: ${response.statusText}`);
    }
    const blob = await response.blob();
    return await new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
  } catch (error) {
    console.warn('[PDF] Failed to load header image', src, error);
    return null;
  }
};

const getImageFormat = (dataUrl) => {
  if (!dataUrl || typeof dataUrl !== 'string') return 'PNG';
  if (dataUrl.startsWith('data:image/jpeg') || dataUrl.startsWith('data:image/jpg')) return 'JPEG';
  if (dataUrl.startsWith('data:image/webp')) return 'WEBP';
  return 'PNG';
};

const formatScore = (value) => {
  if (typeof value === 'number' && Number.isFinite(value)) {
    return Number(value).toFixed(2);
  }
  return '—';
};

const addTitle = (doc, formTitle, logos = {}) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  const marginX = 14;
  const logoWidth = 26;
  const logoHeight = 26;

  if (logos.left?.dataUrl) {
    doc.addImage(logos.left.dataUrl, logos.left.format, marginX, 16 - logoHeight / 2, logoWidth, logoHeight, undefined, 'FAST');
  }
  if (logos.right?.dataUrl) {
    doc.addImage(
      logos.right.dataUrl,
      logos.right.format,
      pageWidth - marginX - logoWidth,
      16 - logoHeight / 2,
      logoWidth,
      logoHeight,
      undefined,
      'FAST'
    );
  }

  doc.setFont('times', 'bold');
  doc.setFontSize(13);
  doc.text('BUKIDNON STATE UNIVERSITY', pageWidth / 2, 18, { align: 'center' });
  doc.setFont('times', 'normal');
  doc.setFontSize(10);
  doc.text('Malaybalay City, Bukidnon, 8700', pageWidth / 2, 23, { align: 'center' });
  doc.text('Tel (088) 813-5661 to 5663; TeleFax (088) 813-2717;', pageWidth / 2, 28, { align: 'center' });
  doc.setTextColor(34, 87, 149);
  doc.text('www.buksu.edu.ph', pageWidth / 2, 33, { align: 'center' });
  doc.setTextColor(0, 0, 0);
  doc.setFont('times', 'italic');
  doc.text('College of Technologies', pageWidth / 2, 38, { align: 'center' });

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text('Evaluation Form Instructor Summary', pageWidth / 2, 48, { align: 'center' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.text(`Evaluation Form: ${formTitle || 'N/A'}`, pageWidth / 2, 54, { align: 'center' });

  doc.setDrawColor(229, 231, 235);
  doc.setLineWidth(0.3);
  doc.line(14, 59, pageWidth - 14, 59);
};

const buildRows = (instructors = []) =>
  instructors.map((instructor, index) => {
    const totalAverage =
      typeof instructor.totalAverage === 'number'
        ? instructor.totalAverage
        : instructor.categoryBreakdown?.totalAverage;
    const ratingEquivalent = instructor.descriptiveRating || instructor.categoryBreakdown?.descriptiveRating || '—';
    const conversionScore =
      typeof instructor.facultyReclassificationScore === 'number'
        ? instructor.facultyReclassificationScore
        : instructor.categoryBreakdown?.facultyReclassificationScore;

    return [
      `${index + 1}. ${instructor.instructorName || 'Unknown Instructor'}`,
      formatScore(totalAverage),
      ratingEquivalent,
      conversionScore != null ? `${conversionScore}` : '—',
    ];
  });

const addInstructorTable = (doc, instructors) => {
  autoTable(doc, {
    head: [['Instructor', 'Total Average', 'Rating Equivalent', 'Faculty Reclassification']],
    body: buildRows(instructors),
    startY: 64,
    theme: 'grid',
    styles: { fontSize: 9, cellPadding: 3 },
    headStyles: { fillColor: [35, 56, 118], textColor: 255 },
    columnStyles: {
      0: { cellWidth: 80 },
      1: { cellWidth: 30, halign: 'center' },
      2: { cellWidth: 40, halign: 'center' },
      3: { cellWidth: 40, halign: 'center' },
    },
    margin: { left: 14, right: 14 },
  });
  return doc.lastAutoTable?.finalY || 64;
};

const addSummary = (doc, payload, startY) => {
  const summaryLines = [
    `Total Instructors: ${payload.totalInstructors ?? 0}`,
    `Total Responses: ${payload.totalResponses ?? 0}`,
    `Generated: ${new Date().toLocaleString()}`,
  ];

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  let currentY = startY + 8;
  summaryLines.forEach((line) => {
    doc.text(line, 14, currentY);
    currentY += 5;
  });

  return currentY;
};

const addFooter = (doc, footerText) => {
  const pageCount = doc.internal.getNumberOfPages();
  for (let pageNumber = 1; pageNumber <= pageCount; pageNumber += 1) {
    doc.setPage(pageNumber);
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(8);
    // Visible digital signature footer
    if (footerText) {
      doc.text(footerText, 14, pageHeight - 13, { maxWidth: doc.internal.pageSize.getWidth() - 28 });
    }
    doc.text(DEFAULT_TAGLINE, 14, pageHeight - 7);
    doc.text(`Page ${pageNumber} of ${pageCount}`, doc.internal.pageSize.getWidth() - 14, pageHeight - 7, {
      align: 'right',
    });
  }
};

const openPdf = (doc, fileName) => {
  try {
    const blob = doc.output('blob');
    const blobUrl = URL.createObjectURL(blob);
    const popup = window.open(blobUrl);

    if (!popup) {
      doc.save(fileName);
      URL.revokeObjectURL(blobUrl);
      return;
    }

    popup.onload = () => {
      setTimeout(() => URL.revokeObjectURL(blobUrl), 60_000);
    };
  } catch (error) {
    console.error('Unable to open PDF in new tab, falling back to download.', error);
    doc.save(fileName);
  }
};

const generateFormSummaryPdf = async (payload) => {
  if (!payload?.instructors?.length) {
    throw new Error('No instructor data was provided.');
  }

  const leftLogoPath = payload?.headerLogos?.left || DEFAULT_LOGO_PATHS.left;
  const rightLogoPath = payload?.headerLogos?.right || DEFAULT_LOGO_PATHS.right;
  const [leftLogoDataUrl, rightLogoDataUrl] = await Promise.all([
    fetchImageAsDataUrl(leftLogoPath),
    fetchImageAsDataUrl(rightLogoPath),
  ]);

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  addTitle(
    doc,
    payload.formTitle,
    {
      left: leftLogoDataUrl ? { dataUrl: leftLogoDataUrl, format: getImageFormat(leftLogoDataUrl) } : null,
      right: rightLogoDataUrl ? { dataUrl: rightLogoDataUrl, format: getImageFormat(rightLogoDataUrl) } : null,
    }
  );
  const tableBottom = addInstructorTable(doc, payload.instructors);
  addSummary(doc, payload, tableBottom);
  // Initial footer without signature, to get stable layout
  addFooter(doc, '');

  // Generate signature over PDF bytes
  const pdfArrayBuffer = doc.output('arraybuffer');
  const user = getCurrentUserForSignature();
  const { footerText, signatureHash, signatureId } = generateDigitalSignature(user, pdfArrayBuffer);

  // Store hash + id in PDF properties (metadata)
  const existingTitle = doc.internal?.getTitle?.() || payload.formTitle || 'Evaluation Form Summary';
  doc.setProperties({
    title: existingTitle,
    subject: 'Digitally signed evaluation form summary',
    author: user.email,
    keywords: `digital-signature,sha256,SignatureID=${signatureId},SignatureHash=${signatureHash}`,
    creator: 'Buksu IT Instructor Evaluation System',
  });

  // Rewrite footer with real signature text
  addFooter(doc, footerText);

  const fileName = `evaluation-form-summary-${new Date().toISOString().split('T')[0]}.pdf`;
  openPdf(doc, fileName);
};

export default generateFormSummaryPdf;

