import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { generateDigitalSignature, getCurrentUserForSignature } from './signature';

const DEFAULT_TAGLINE = 'Generated by the Dean Dashboard System';
const DEFAULT_LOGO_PATHS = {
  left: '/buksu-logo.png',
  right: '/cot-logo.jpg',
};

const resolveAssetPath = (src) => {
  if (!src) return null;
  if (src.startsWith('data:') || /^https?:\/\//i.test(src)) {
    return src;
  }
  const baseUrl = typeof window !== 'undefined' ? window.location.origin : '';
  if (!baseUrl) {
    return src.startsWith('/') ? src : `/${src}`;
  }
  return src.startsWith('/') ? `${baseUrl}${src}` : `${baseUrl}/${src}`;
};

const fetchImageAsDataUrl = async (src) => {
  if (!src) return null;
  const resolved = resolveAssetPath(src);
  try {
    const response = await fetch(resolved, { cache: 'force-cache' });
    if (!response.ok) {
      throw new Error(`Unable to load logo: ${response.statusText}`);
    }
    const blob = await response.blob();
    return await new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
  } catch (error) {
    console.warn('[Department PDF] Failed to load header image', src, error);
    return null;
  }
};

const getImageFormat = (dataUrl) => {
  if (!dataUrl || typeof dataUrl !== 'string') return 'PNG';
  if (dataUrl.startsWith('data:image/jpeg') || dataUrl.startsWith('data:image/jpg')) return 'JPEG';
  if (dataUrl.startsWith('data:image/webp')) return 'WEBP';
  return 'PNG';
};

const formatScore = (value) => {
  if (typeof value === 'number' && Number.isFinite(value)) {
    return Number(value).toFixed(2);
  }
  return '—';
};

const asText = (value, fallback = 'Not specified') => {
  if (value === 0) return '0';
  return value ? String(value) : fallback;
};

const addHeader = (doc, payload = {}, logos = {}) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  const marginX = 14;
  const centerX = pageWidth / 2;
  let currentY = 20;

  const logoHeight = 26;
  const logoWidth = 26;

  if (logos.left?.dataUrl) {
    doc.addImage(
      logos.left.dataUrl,
      logos.left.format,
      marginX,
      currentY - logoHeight / 2,
      logoWidth,
      logoHeight,
      undefined,
      'FAST'
    );
  }
  if (logos.right?.dataUrl) {
    doc.addImage(
      logos.right.dataUrl,
      logos.right.format,
      pageWidth - marginX - logoWidth,
      currentY - logoHeight / 2,
      logoWidth,
      logoHeight,
      undefined,
      'FAST'
    );
  }

  doc.setFont('times', 'bold');
  doc.setFontSize(12);
  doc.text('BUKIDNON STATE UNIVERSITY', centerX, currentY, { align: 'center' });

  doc.setFont('times', 'normal');
  doc.setFontSize(10);
  doc.text('Malaybalay City, Bukidnon, 8700', centerX, currentY + 5, { align: 'center' });
  doc.text('Tel (088) 813-5661 to 5663; TeleFax (088) 813-2717;', centerX, currentY + 10, { align: 'center' });

  doc.setTextColor(34, 87, 149);
  doc.text('www.buksu.edu.ph', centerX, currentY + 15, { align: 'center' });
  doc.setTextColor(0, 0, 0);

  doc.setFont('times', 'italic');
  doc.text('College of Technologies', centerX, currentY + 21, { align: 'center' });

  currentY += 32;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text('Instructor Performance in College of Technology', centerX, currentY, { align: 'center' });

  currentY += 8;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(`Evaluation Form: ${asText(payload.formTitle, 'Evaluation Form')}`, centerX, currentY, { align: 'center' });

  currentY += 4;
  doc.setFontSize(9);
  doc.text(`Generated: ${asText(payload.generatedAt)}`, centerX, currentY, { align: 'center' });

  return currentY + 6;
};

const addDepartmentTables = (doc, payload, startY) => {
  const rawDepartments = Array.isArray(payload.departments) ? payload.departments : [];
  const departments = rawDepartments
    .slice()
    .sort((a, b) => asText(a.name, '').localeCompare(asText(b.name, ''), undefined, { sensitivity: 'base' }))
    .map((dept) => ({
      ...dept,
      instructors: (dept.instructors || [])
        .slice()
        .sort((a, b) => asText(a.name, '').localeCompare(asText(b.name, ''), undefined, { sensitivity: 'base' })),
    }));
  if (!departments.length) {
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(10);
    doc.text('No department data available.', 14, startY + 10);
    return startY + 20;
  }

  const pageHeight = doc.internal.pageSize.getHeight();
  const pageWidth = doc.internal.pageSize.getWidth();
  const tableWidth = pageWidth - 28; // respect 14mm margins on each side
  let currentY = startY;

  departments.forEach((department, index) => {
    // Check if we need a new page (only if there's not enough space for the department header and table)
    if (currentY > pageHeight - 60) {
      doc.addPage();
      currentY = 20;
    }

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text(`${index + 1}. ${asText(department.name, 'Unspecified Department')}`, 14, currentY);
    currentY += 6;

    const rows = (department.instructors || []).length
      ? department.instructors.map((instructor) => [
          asText(instructor.name, 'Unknown Instructor'),
          formatScore(instructor.totalAverage),
          asText(instructor.ratingEquivalent, '—'),
          instructor.reclassification !== undefined && instructor.reclassification !== null
            ? `${instructor.reclassification}`
            : '—',
        ])
      : [['No instructors in this department', '—', '—', '—']];

    autoTable(doc, {
      head: [['Instructor', 'Total Average', 'Rating Equivalent', 'Faculty Reclassification']],
      body: rows,
      startY: currentY,
      theme: 'grid',
      styles: { fontSize: 9, cellPadding: 3, valign: 'middle' },
      headStyles: { fillColor: [35, 56, 118], textColor: 255 },
      columnStyles: {
        0: { cellWidth: 68 },
        1: { cellWidth: 32, halign: 'center' },
        2: { cellWidth: 50, halign: 'center' },
        3: { cellWidth: 32, halign: 'center' },
      },
      margin: { left: 14, right: 14 },
      tableWidth,
    });

    currentY = doc.lastAutoTable?.finalY || currentY;
    currentY += 10;
  });

  return currentY;
};

const addFooter = (doc, tagline = DEFAULT_TAGLINE, footerText = '') => {
  const pageCount = doc.internal.getNumberOfPages();

  for (let pageNumber = 1; pageNumber <= pageCount; pageNumber += 1) {
    doc.setPage(pageNumber);
    const pageHeight = doc.internal.pageSize.getHeight();
    const pageWidth = doc.internal.pageSize.getWidth();

    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    if (footerText) {
      doc.text(footerText, 14, pageHeight - 13, { maxWidth: pageWidth - 28 });
    }
    doc.text(tagline, 14, pageHeight - 7);
    doc.text(`Page ${pageNumber} of ${pageCount}`, pageWidth - 14, pageHeight - 7, {
      align: 'right',
    });
  }
};

const openPdf = (doc, fileName) => {
  try {
    const blob = doc.output('blob');
    const blobUrl = URL.createObjectURL(blob);
    const popup = window.open(blobUrl);

    if (!popup) {
      doc.save(fileName);
      URL.revokeObjectURL(blobUrl);
      return;
    }

    popup.onload = () => {
      setTimeout(() => URL.revokeObjectURL(blobUrl), 60_000);
    };
  } catch (error) {
    console.error('Unable to open PDF in new tab, falling back to download.', error);
    doc.save(fileName);
  }
};

const generateDepartmentPerformancePdf = async (payload) => {
  if (!payload) {
    throw new Error('Cannot generate PDF without payload data.');
  }

  const leftLogoPath = payload?.headerLogos?.left || DEFAULT_LOGO_PATHS.left;
  const rightLogoPath = payload?.headerLogos?.right || DEFAULT_LOGO_PATHS.right;

  const [leftLogoDataUrl, rightLogoDataUrl] = await Promise.all([
    fetchImageAsDataUrl(leftLogoPath),
    fetchImageAsDataUrl(rightLogoPath),
  ]);

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const headerBottom = addHeader(
    doc,
    payload,
    {
      left: leftLogoDataUrl ? { dataUrl: leftLogoDataUrl, format: getImageFormat(leftLogoDataUrl) } : null,
      right: rightLogoDataUrl ? { dataUrl: rightLogoDataUrl, format: getImageFormat(rightLogoDataUrl) } : null,
    }
  );

  addDepartmentTables(doc, payload, headerBottom + 6);
  // First pass footer for layout
  addFooter(doc, DEFAULT_TAGLINE, '');

  const pdfArrayBuffer = doc.output('arraybuffer');
  const user = getCurrentUserForSignature();
  const { footerText, signatureHash, signatureId } = generateDigitalSignature(user, pdfArrayBuffer);

  doc.setProperties({
    title: `Department Performance - ${asText(payload.formTitle, 'Evaluation Form')}`,
    subject: 'Digitally signed department performance report',
    author: user.email,
    keywords: `digital-signature,sha256,SignatureID=${signatureId},SignatureHash=${signatureHash}`,
    creator: 'Buksu IT Instructor Evaluation System',
  });

  // Apply final footer with signature text
  addFooter(doc, DEFAULT_TAGLINE, footerText);

  const normalizedTitle = asText(payload.formTitle, 'department-report')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    || 'department-report';

  const fileName = `department-performance-${normalizedTitle}.pdf`;
  openPdf(doc, fileName);
};

export default generateDepartmentPerformancePdf;

